server:
  port: 8080

spring:
  mvc:
    static-path-pattern: /static/** 
  datasource:
    url: jdbc:mysql://localhost:3306/cm_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html    
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,templates/** 
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 6000
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 2       
                  
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.demo.model